# Site settings
title: Ateneo Renewable Energy and Engineering for Sustainability Group
header-img: img/home-bg.jpg
email: ateneo.rees.group@gmail.com
copyright_name: A*REES
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "https://ateneorees.github.io"
url: "https://ateneorees.github.io"
twitter_username: 
github_username:  ateneorees
facebook_username:  none
email_username:  ateneo.rees.group@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
